language: node_js
node_js:
- '8.11.3'
env:
  global:
    secure: xYVVEHW29XlJT3ukibCHmcFlUzzGxvLcQfB/CEO5X8Tzz+KhN08csmxrOTkl5ziyqoVT6o9gNykiIy/p+Tq4bBXLvqRSX/EfSgj1KZUuWZJ3fi2JIsCxPl5MMHlY8d+UUVOoSpHw6eboH0NqezkrzXTgRCyT/TdUbFwsPcXxXocgDuSUSVbIdCj2RPfGvJaGRswxjJwSlCoSWXnhs2mebMWU7fp1gmihGqCoivFXUpGhhI6bQsUQK/m6L66Mp3Vk7cWwaG8n1bilygFZuD+BX6R7CH/RMzcp6u2hJpKTpyywD69sUgRlhP4JWOeEd9Sa9incPE2VZN7wJTzR6x3w+zkLAMiZrYYJcDQuB3BrLfcPo4WZ9hc2hTa4QUtX544e4uHoOqB6efQdjENtr4GrWpJN55iGAtRsvYxzXlEJbaI+JOcNdfcXeYC0o9ixC6OkDgBpgnqf5AlvDOQ3TZsrc7kKXQPrM+4XrAHLgnC8aPTfhy2W8wrMun9Z1/80sO3Q+5qs+MBQv7dnZLVwr+uKGDH/kTp0GZse6fwl80wYREBlvGcCc9HNqOxkMJKESm4fvsuEHeVWd9axkS7mW/vxO7xONa4zg+vAW8x7bztN2KILU/bpdC9UEc9LngTjY+QFwOl/c11jdeAydQYHzdaF4oYPfwr5aIN9Mn9yUoTpHyo=
